### ISSUE TITLE
Rainfence.rmskin file available to download?

### ISSUE THREAD

**Issue by e-t-l** [deathcrafter/RainRepo#1]
Hi Shaktijeet/@deathcrafter, this repo looks really cool but I'm not sure how to use it. Is it possible to download the .rmskin file for rainfence? Do I have to build it myself? Thanks!

**Comment by deathcrafter** [comment]
@e-t-l Thanks for reaching out. Sorry for the inconvenience. Here is how to use it:

You paste this in powershell and change the parameters as you see fit.

To change an existing fence's rows and columns you can re-run this command with the same parameters as before changing only rows and columns, and enter Y when it asks whether you want to override.

```ps1
&([scriptblock]::Create((Invoke-WebRequest -UseBasicParsing -Uri "https://raw.githubusercontent.com/deathcrafter/RainRepo/main/RainFences.ps1").Content)) -name "NameOfSkin" -title "TitleOnFence" -rows 3 -columns 4 -folder "path\to\shortcuts\folder" -skinspath "(optional, for portable user)path\to\skins\folder"
```

P.S. for copying path to shortcut folder, shift+right click on (not in) the folder and `Copy as path`.

**Comment by e-t-l** [comment]
Thanks, works like a charm! (I do suggest pinning this issue or adding the above instructions to the repo Readme)

**Comment by deathcrafter** [comment]
> Thanks, works like a charm! (I do suggest pinning this issue or adding the above instructions to the repo Readme)

Will do. Tho if you got me from Discord, I already put the instructions there. If you got it from some where else can I know where?
